In [53]:
import jax
import jax.numpy as jnp
from jax.tree_util import Partial
import numpy as np
import plastix as px

In [24]:
def func(a,b):
    b = b.at[0].set(a[0])
    return jnp.sum(b**2)

In [50]:
half = Partial((jnp.divide), 2)

In [51]:
half(3)

DeviceArray(0.6666667, dtype=float32)

In [34]:
add_one = jax.jit(Partial(jnp.add, 1))

In [25]:
a = jnp.zeros((3,))
b = jnp.ones((3,))

In [26]:
jax.grad(func, argnums=1)(a,b)

DeviceArray([0., 2., 2.], dtype=float32)

In [11]:
edges = [(0,0), (1,0), (0, 1)]
sorted(edges, key = lambda x: x[1])

[(0, 0), (1, 0), (0, 1)]

In [21]:
a = 499
a+1%500

500

In [43]:
key = jax.random.PRNGKey(0)
jax.random.normal(key, (2,3))

DeviceArray([[ 0.18784384, -1.2833426 ,  0.6494181 ],
             [ 1.2490593 ,  0.24447003, -0.11744965]], dtype=float32)

In [46]:
a = jnp.ones((1))
print(a.shape)
a = jnp.squeeze(a)
print(a)

(1,)
1.0


In [30]:
aa = [1, 2, 3]
aa.insert(0, 0)
aa

[0, 1, 2, 3]

In [19]:
w.shape

(3, 2)

In [24]:
a = 2; b =3; c = 5
result = jnp.outer(jnp.outer(jnp.array([a**0, a**1, a**2]), jnp.array([b**0, b**1, b**2])), jnp.array([c**0, c**1, c**2]))
result = jnp.reshape(result, (3,3,3))
result

DeviceArray([[[  1,   5,  25],
              [  3,  15,  75],
              [  9,  45, 225]],

             [[  2,  10,  50],
              [  6,  30, 150],
              [ 18,  90, 450]],

             [[  4,  20, 100],
              [ 12,  60, 300],
              [ 36, 180, 900]]], dtype=int32)

In [37]:
np.round(np.random.rand(5))

array([0., 1., 1., 1., 1.])

In [25]:
result.shape

(3, 3, 3)

In [26]:
A = jnp.ones((3,3,3))

In [33]:
# a^i, b^j, c^k
jnp.multiply(result, A)[0][1][0]

DeviceArray(3., dtype=float32)

In [28]:
n=26
for n in range(27):
    print((n/9)%3, (n/3)%3, n%3)

0.0 0.0 0
0.1111111111111111 0.3333333333333333 1
0.2222222222222222 0.6666666666666666 2
0.3333333333333333 1.0 0
0.4444444444444444 1.3333333333333333 1
0.5555555555555556 1.6666666666666667 2
0.6666666666666666 2.0 0
0.7777777777777778 2.3333333333333335 1
0.8888888888888888 2.6666666666666665 2
1.0 0.0 0
1.1111111111111112 0.3333333333333335 1
1.2222222222222223 0.6666666666666665 2
1.3333333333333333 1.0 0
1.4444444444444444 1.333333333333333 1
1.5555555555555556 1.666666666666667 2
1.6666666666666667 2.0 0
1.7777777777777777 2.333333333333333 1
1.8888888888888888 2.666666666666667 2
2.0 0.0 0
2.111111111111111 0.33333333333333304 1
2.2222222222222223 0.666666666666667 2
2.3333333333333335 1.0 0
2.4444444444444446 1.333333333333333 1
2.5555555555555554 1.666666666666667 2
2.6666666666666665 2.0 0
2.7777777777777777 2.333333333333334 1
2.888888888888889 2.666666666666666 2


In [29]:
int(0.7)

0

In [3]:
def loss(y, pred):
    return (y-pred)**2

In [11]:
grad_loss = jax.grad(loss)
grad_loss(1.0, 0.9)

DeviceArray(0.20000005, dtype=float32, weak_type=True)

In [13]:
round(0.7)

1

In [36]:
w = jnp.ones((2,2))
key = jax.random.PRNGKey(0)
x = jax.random.normal(key, (2,))

In [37]:
print('w: ', w)
print('x: ', x)
w @ x

w:  [[1. 1.]
 [1. 1.]]
x:  [-0.78476596  0.85644484]


DeviceArray([0.07167888, 0.07167888], dtype=float32)

In [32]:
jnp.multiply(x, y)

DeviceArray([-0.78476596,  0.85644484], dtype=float32)

In [38]:
w.reshape(-1)

DeviceArray([1., 1., 1., 1.], dtype=float32)

In [48]:
class Banana:
    def __init__(self):
        self.sweet = 0.5
        self.ripe = 1
        self.country = 'India'

    @classmethod
    def fertilizer(self):
        if(self.sweet == 0.5):
            print('AE34')
    
    def func1(self):
        pass
    
    def func2():
        pass
    

In [53]:
b1 = Banana()
Banana.fertilizer()

AttributeError: type object 'Banana' has no attribute 'sweet'

In [25]:

jax.vmap(jax.grad(loss), in_axes=(None, 0, 0), out_axes=0)

NameError: name 'loss' is not defined

In [15]:
import abc

class Kernel(abc.ABC):
    @classmethod
    def print_attributes(cls):
        print(cls.__dict__.items())
        
        
class EdgeKernel(Kernel):

class FixedWeight(EdgeKernel)
    
e1 = EdgeKernel()
e2 = EdgeKernel()